name: Dispatch Source Code

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Send Dispatch Event
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PAT }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/drshooby/Sharenet-Vue-Spa-Infra/dispatches \
                 -d '{"event_type":"deploy","client_payload":{"ref":"main"}}'
  
    
